---
# tasks file for cleanup
- name: cleanup
  block:
    - name: Unmount {{app_name}} image
      command: hdiutil detach "{{mount_path}}/{{app_name}}"
    - file: path={{downloads}} state=absent
    