---
- name: Create Ansible downloads directory
  file: 
    path: "{{downloads}}"
    state: directory
- name: Download {{app_name}} to {{downloads}}
  get_url: 
    url: "{{app_url}}"
    dest: "{{downloads}}/{{app_name}}.{{download_file_type}}"
- include: unzip.yml
  when: download_file_type == "zip"
- include: find_installer.yml
- include: mount.yml
  when: installer_type == ".dmg"
- name: Install package {{app_name}}
  shell: installer -pkg "{{installer}}" -target /
  when: installer_type == ".pkg"
- name: Copy {{app_name}} to Applications directory
  copy:
    remote_src: yes
    src: "{{installer}}"
    dest: /Applications
    force: no
  when: installer_type == ".app"
- name: Clear Ansible downloads directory
  block:
    - name: Unmount {{app_name}} image
      command: hdiutil detach "{{mount_path}}/{{app_name}}"
    - file: path={{downloads}} state=absent
