---
- command: whoami
  become: no
  register: homebrew_user
- name: Install {{brew_cask_name}} with brew-cask
  block:
    - name: allow passwordless sudo
      lineinfile:
        path: /etc/sudoers.d/tmp-ansible
        line: '{{ homebrew_user.stdout }} ALL=(ALL) NOPASSWD: ALL'
        create: yes
      become: yes
    - name: Upgrade {{brew_cask_name}} with brew-cask
      homebrew_cask: name={{brew_cask_name}}
      become: no
  always:
    - name: disable passwordless sudo
      file:
        path: /etc/sudoers/tmp-ansible
        state: absent
      become: yes
