- name: Find unzipped files
  find:
    paths: "{{downloads}}/"
  register: fileslist
- name:
  set_fact: installer={{fileslist.files[0].path}}
- name:
  set_fact: installer_type={{installer | splitext | last}}
