---
# tasks file for roles
- include: download.yml
- include: unzip.yml
  when: download_file_type == "zip"
- include: rm_dup.yml
- include: mount.yml
  when: download_file_type == "dmg"
- include: app.yml
  when: installer_type == "app"
- include: unmount.yml
  when: download_file_type == "dmg"