---
# tasks file for setup
- name: Create Ansible downloads directory
  file: path={{downloads}} state=directory
- name: Setting installer source to "{{downloads}}"
  set_fact:
    installer_source: "{{downloads}}"