---
- hosts: local
  become: yes
  vars:
    app_name: Firefox
    app_url: https://download.mozilla.org/?product=firefox-latest-ssl&os=osx&lang=en-US
    installer_type: app
    install_method: dmg
    download_file_type: dmg
  roles:
    - setup
    - installer
    - cleanup
   