---
- name: Install Google Chrome
  hosts: local
  become: yes
  vars:
    app_name: Google Chrome
    app_url: https://dl.google.com/chrome/mac/stable/CHFA/googlechrome.dmg
    installer_type: app
    install_method: dmg
    download_file_type: dmg
  roles: 
    - setup
    - installer
    - cleanup