---
- import_playbook : playbooks/firefox.yml
- import_playbook : playbooks/google_chrome.yml
- import_playbook : playbooks/slack.yml
- import_playbook : playbooks/teams.yml
- import_playbook : playbooks/visual_studio_code.yml
- import_playbook : playbooks/office365.yml