---
- hosts: local
  become: yes
  vars:
    app_name: Postman
    app_url: https://dl.pstmn.io/download/latest/osx
    installer_type: app
    download_file_type: zip
    install_method: dmg
  roles:
    - setup
    - installer
    - cleanup
   