---
- hosts: local
  become: yes
  vars:
    app_name: Visual Studio Code
    app_url: https://go.microsoft.com/fwlink/?LinkID=620882
    installer_type: app
    install_method: dmg
    download_file_type: zip
  roles:
    - setup
    - installer
    - cleanup